image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [236.95549,  -0.23185, 325.85003,
           0.     , 236.52024, 256.72288,
           0.     ,   0.     ,   1.     ]
# camera_model: fisheye
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 4
  data: [-0.084069, 0.040169, -0.025960, 0.005631]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [236.95549,  -0.23185, 325.85003,   0.     ,
           0.     , 236.52024, 256.72288,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
