<?xml version="1.0"?>

<robot name="pantilt" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find dual_ubiquitous_display_description)/urdf/pantilt/pantilt.transmission.xacro"/>
  <xacro:include filename="$(find dual_ubiquitous_display_description)/urdf/pantilt/pantilt.gazebo.xacro"/>


  <xacro:property name="base_to_box_height" value="0.066"/>
  <xacro:property name="box_to_proj_height" value="0.17"/>

  <material name="red" >
    <color rgba="0.7 0.0 0.7 1.0" />
  </material>
  <material name="blue" >
    <color rgba="0.0 0.7 0.7 1.0" />
  </material>
  <material name="green" >
    <color rgba="0.0 0.7 0.7 1.0" />
  </material>
  <material name="gray" >
    <color rgba="0.7 0.7 0.7 1.0" />
  </material>

  <xacro:macro name="pantilt_model" params="name parent pos offset">

    <link name="${name}base_link" >
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.07 0.085 0.065" /-->
          <mesh filename="package://dual_ubiquitous_display_description/meshes/STL/pantilt/pantilt2_base_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 ${base_to_box_height/2}" rpy="0 0 0"/>
       <mass value="0.78"/>
       <inertia
	    ixx="0.00190" ixy="0.0" ixz="0.0"
	    iyy="0.00202" iyz="0.0"
	    izz="0.00152"/>
     </inertial>
    </link>

    <joint name="${parent}_to_${name}base_link" type="fixed">
      <origin xyz="${pos} 0 0.372 " rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="${name}base_link"/>
    </joint>

    <link name="${name}pan_link" >
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.07 0.085 0.065" /-->
          <mesh filename="package://dual_ubiquitous_display_description/meshes/STL/pantilt/pan_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 ${base_to_box_height/2}" rpy="0 0 0"/>
       <mass value="0.78"/>
       <inertia
	    ixx="0.00190" ixy="0.0" ixz="0.0"
	    iyy="0.00202" iyz="0.0"
	    izz="0.00152"/>
     </inertial>
    </link>

    <joint name="${name}pan_joint" type="revolute">
      <parent link="${name}base_link"/>
      <child link="${name}pan_link"/>
      <origin xyz="0 0 0.047" rpy="0 0 ${-offset}" />
      <axis xyz="0 0 1" />
      <limit lower="-2.9670" upper="2.9670" effort="41" velocity="1"/>
      <!--<safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />-->
      <dynamics damping="0.7"/>
    </joint>

    <link name="${name}tilt_link" >
      <visual>
        <origin xyz=" 0 0 0" rpy="1.57 0 0" />
        <geometry>
          <!--box size="0.07 0.085 0.065" /-->
          <mesh filename="package://dual_ubiquitous_display_description/meshes/STL/pantilt/tilt_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="-0.250 0 0.118" rpy="0 0 0"/>
       <mass value="0.78"/>
       <inertia
      ixx="0.00190" ixy="0.0" ixz="0.0"
      iyy="0.00202" iyz="0.0"
      izz="0.00152"/>
     </inertial>
    </link>

    <joint name="${name}tilt_joint" type="revolute">
      <parent link="${name}pan_link"/>
      <child link="${name}tilt_link"/>
      <origin xyz="0.093 0 0.195" rpy="0 -1.57 0" />
      <axis xyz="0 0 1" />
      <limit lower="-1.3" upper="1.3" effort="10" velocity="1"/>
      <!--<safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />-->
      <dynamics damping="0.7"/>
    </joint>

    <link name="${name}projector_plugin_optical_link" >
    </link>

    <joint name="${name}tilt_link_to_${name}projector_plugin_optical_link" type="fixed">
      <origin xyz="0 0 0.093 " rpy="-1.57 3.14 0" />
      <parent link="${name}tilt_link"/>
      <child link="${name}projector_plugin_optical_link"/>
    </joint>

    <xacro:dual_ubiquitous_display_transmission name="${name}"/>
    <xacro:pantilt_gazebo name="${name}"/>
  </xacro:macro>

</robot>
